In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vaishnavi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [4]:
dataset = pd.read_csv("training.1600000.processed.noemoticon.csv" , encoding= 'ISO-8859-1')

In [5]:
dataset.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [6]:
col_names = ['target' , 'id' , 'date' , 'flag' , 'user' , 'text']
dataset.columns = col_names

In [7]:
dataset.head()

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [8]:
dataset.shape

(1599999, 6)

In [9]:
#checking for missing values
dataset.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [10]:
# Distribution of tweets
dataset['target'].value_counts()

target
4    800000
0    799999
Name: count, dtype: int64

In [11]:
# Converting 0 to -ve and 4 to +ve
dataset['target'] = dataset['target'].map({0:0 , 4:1})

In [12]:
dataset['target'].value_counts()

target
1    800000
0    799999
Name: count, dtype: int64

In [13]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def stemming(content):
    content = re.sub('[^a-zA-Z]', ' ', content)
    words = content.lower().split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

In [14]:
dataset['text'] = dataset['text'].apply(stemming)

In [15]:
dataset.head()

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,upset update facebook texting might cry result...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,kenichan dived many times ball managed save re...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,whole body feels itchy like fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,nationwideclass behaving mad see
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,kwesidei whole crew

In [16]:
x = dataset['text']
y = dataset['target']

In [17]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

x_train = vectorizer.fit_transform(x_train)   # learn + transform
x_test = vectorizer.transform(x_test)         # only transform

In [19]:
print(x_train)

  (0, 489922)	0.22296740830054296
  (0, 167764)	0.18489397680768677
  (0, 166772)	0.14554214889440525
  (0, 434301)	0.1964075859758828
  (0, 271024)	0.508332542294945
  (0, 466307)	0.4149719841690795
  (0, 178672)	0.19199825692967853
  (0, 423757)	0.3805909779537499
  (0, 162358)	0.49398861411697653
  (1, 461007)	0.7653418627923502
  (1, 191674)	0.6436239842155785
  (2, 46359)	0.5185642026868234
  (2, 167865)	0.2094850856795508
  (2, 318841)	0.2492112488293298
  (2, 302994)	0.38659195236504
  (2, 448626)	0.6896720832345782
  (3, 194956)	0.41274233244411623
  (3, 348552)	0.4954159399804303
  (3, 441309)	0.21183902940202232
  (3, 320887)	0.3967342022897316
  (3, 150863)	0.20613593745226905
  (3, 99467)	0.4954159399804303
  (3, 194953)	0.3066007721474584
  (4, 170609)	0.16091679079647347
  (4, 103962)	0.1292615840716845
  :	:
  (1279995, 274108)	0.7012380888729534
  (1279995, 112890)	0.712927165083368
  (1279996, 450426)	0.2038938185822348
  (1279996, 491188)	0.19856791304109223
  (1279996, 187412)	0.2202316368743686
  (1279996, 423598)	0.2165279315243917
  (1279996, 189395)	0.2717534807813773
  (1279996, 254442)	0.27890852007462247
  (1279996, 480568)	0.26186093510708947
  (1279996, 150232)	0.38759732631493043
  (1279996, 304624)	0.6731782988593825
  (1279997, 266214)	0.18099830942332645
  (1279997, 267776)	0.23587439913420624
  (1279997, 368067)	0.19281384055131393
  (1279997, 294072)	0.203641241607909
  (1279997, 34073)	0.18563934266872978
  (1279997, 305985)	0.2037717641777232
  (1279997, 349534)	0.48073934212851355
  (1279997, 86845)	0.22013325502553205
  (1279997, 403127)	0.3443953094089053
  (1279997, 449428)	0.4454539946680607
  (1279997, 24653)	0.4004556085982025
  (1279998, 168080)	0.36621971643897994
  (1279998, 433990)	0.4949965650788224
  (1279998, 396924)	0.7879476631423691

In [20]:
# Training the model
model = LogisticRegression()
model.fit(x_train , y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
# Testing the model
y_pred = model.predict(x_test)
print(accuracy_score(y_test , y_pred))

0.780334375

In [22]:
from nltk.corpus import stopwords
import re

stop_words = set(stopwords.words('english'))  # load once

def predict_sentiment(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.lower().split()
    
    # remove stopwords (FAST)
    words = [word for word in words if word not in stop_words]
    
    text = " ".join(words)
    
    vector = vectorizer.transform([text])
    sentiment = model.predict(vector)
    
    return "Negative" if sentiment[0] == 0 else "Positive"

In [23]:
# Testing the model
print(predict_sentiment("I hate you"))
print(predict_sentiment("I love you"))

Negative
Positive

In [24]:
# Save the model
import pickle
pickle.dump(model , open('model.pkl' , 'wb'))

In [25]:
pickle.dump(vectorizer , open('vectorizer.pkl' , 'wb'))